import './globals.css'
import { Inter } from 'next/font/google'
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <main className='content'>
          <Header />
          {children}
          <Footer />
        </main>


      </body>
    </html>
  )
}
